[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]

[start]
cmd = "python3 -m gunicorn dashboard_with_status:app --bind 0.0.0.0:${PORT:-5000}"