[providers]
python = "3.11"

[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn dashboard_with_status:app --bind 0.0.0.0:${PORT:-5000}"